
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer"
import ClientProviders from "@/components/clientProvider";
import { ToastContainer, toast } from 'react-toastify';
import UserDetailsFetcher from "../components/userDetailsFetch"
// import { useEffect } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
  <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
    <ClientProviders> 
      <UserDetailsFetcher />
      <ToastContainer />
      <Header />
      <main className="min-h-[calc(100vh-120px)] pt-16">
        {children}
      </main>
      <Footer />
    </ClientProviders>
  </body>
</html>

  );
}
